image: magento/magento2devbox-web
#TODO: create an image with deployer and composer installed


pipelines:
    custom:
        deploy-staging:
            - step:
                name: Deploy to Staging on Hypernode
                deployment: staging
                script:
                    - curl -LO https://deployer.org/deployer.phar
                    - mv deployer.phar /usr/local/bin/dep
                    - chmod +x /usr/local/bin/dep
                    - dep deploy staging
        deploy-production:
            - step:
                name: Deploy to Production on Hypernode
                deployment: production
                script:
                    - curl -LO https://deployer.org/deployer.phar
                    - mv deployer.phar /usr/local/bin/dep
                    - chmod +x /usr/local/bin/dep
                    - dep deploy production